apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd-wp-mysql  # 
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kube.*
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kube.**>
      @type record_transformer
      <record>
        container_name ${record["kubernetes"]["container_name"]}
        namespace_name ${record["kubernetes"]["namespace_name"]}
        pod_name ${record["kubernetes"]["pod_name"]}
      </record>
    </filter>

    <match **>
      @type forward
      <server>
        host 172.16.13.82
        port 514
      </server>
    </match>